### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by mgn2109** [odf/gavrog#11]
Hello,

Your 3dt program looks like a wonderful visualization tool that I would like to use, but it's a bit difficult to install.  I was wondering if there were any plans for an updated version, or if not, would you have a suggestion of another '3dt-like' software?

What I'm hoping for is a visualization tool with preprogrammed nets from the resource http://rcsr.anu.edu.au/ to poke around with.  I'm particularly interested in visualizing tilings.

Thank you for your time!

**Comment by odf** [comment]
Unfortunately, 3dt is a casualty of 64-bit Java, among other things. It ended up being too hard to maintain, and I decided instead to focus on my new project webGavrog. It is not yet at the point where it can completely replace 3dt, but I think it's approaching usefulness. Unlike 3dt, it can display nets directly, not just in association with tilings.

See https://github.com/odf/webGavrog for the code and http://gavrog.org/webGavrog/ for an online version. A file with all applicable RCSR nets can be downloaded from http://rcsr.net/systre as "Systre input data (.cgd)" and then opened in webGavrog.

I hope that helps.

**Comment by mgn2109** [comment]
Ah thank you, this looks fantastic.  One quick question I have is that when importing the database, when trying to include tiles, a majority of the net just disappears.  Have tilings displays not been implemented yet?

Thank you again for your time.

**Comment by odf** [comment]
You mean via "Add Tile(s)" in the context menu? That's a bug I hadn't been aware of, so thanks for letting me know. In general, webGavrog right now strictly distinguishes between nets and tilings (which require a different kind of input file), so that menu item shouldn't even be there. It's early days, so unfortunately there are some rough edges.

**Comment by mgn2109** [comment]
I understand, thank you for the clarification.  So for now, webGavrog exclusively displays nets from the entire rcsr database (via that systre download file you mentioned）but not the associated tilings at the same time?  I'm particularly interested in being able to write down the abstract graph defined by the tilings (i.e. the edges as pairs of vertices, the faces as lists of edges, etc.).  I've been combing through the code since that information should be stored implicitly when rendering, but I was wondering if you had a suggestion as to where to look?

Also, one other small bug I came across is that when searching, webGavrog will always load the first instance of a name.  For example, if pcu occurs after pcu-a, it will always load pcu-a when searching pcu (although this can be easily worked around by modifying the names in the cdg file directly).

**Comment by odf** [comment]
I've changed the search so that the whole name of the structure must be matched (i.e. "srs" now only matches srs, but not srs-a etc.). That's still not ideal but maybe will lead to slightly less surprising results. I'm still trying to decide on the best way to handle searches with multiple results.

There are some examples of tilings, including a large list from RCSR, here: https://github.com/odf/gavrog/tree/master/Deploy/Data.

The way tilings are stored internally is a little more complicated than one would suspect. Here is an introduction to the data structure with references to more in-depth material: http://gavrog.org/TCS.pdf.

**Comment by mgn2109** [comment]
I see, I'll read over this to try and understand how to recover the underlying graph.  It's remarkable that such beautiful tilings can be generated from such simple input files.

Thank you again for the resource.

**Comment by leoadec** [comment]
Hello,

I've been using the database at https://github.com/odf/gavrog/tree/master/Deploy/Data to visualize the tilings for some self-dual nets, but I noticed that non-natural self-dual tilings mentioned in the RCSR webpage are not present. I wonder if there's a similar database including the non-natural self-dual tilings, or if they can be generated in Gavrog directly?

Thanks!

**Comment by odf** [comment]
We are working on making a more complete collection of tilings available on the RCSR web site. I cannot give a specific time line on that right now, but it's a relatively high priority.
